LokasWiki/LokasBot

statistics/list_of_wikipedians_by_number_of_revision_edits.py
statistics/stub/list_of_wikipedians_by_number_of_revision_edits.txt

+ويكيبيديا:قائمة الويكيبيديين حسب عدد مراجعة التعديلات

add new page

---

statistics/list_of_wikipedians_by_number_of_revision_edits.py

اصلاح اسم الصفحه وال COLLATE الخاص باسماء البوتات وايضا جعل الاستعلم يتاجهل بوت الترحيب والنيو مساج

fix title of page and COLLATE

---

users_this_week/README.md
users_this_week/daily.py
users_this_week/data.py
users_this_week/module.py
users_this_week/stub/archive.txt
users_this_week/stub/main_page.txt
users_this_week/week.py

init users_this_week (beta)

---

statistics/stub/pages_that_are_missing_internal_links.txt
statistics/stub/users_by_number_of_help_pages_creation.txt
statistics/stub/users_by_number_of_help_pages_creation_with_bot.txt
statistics/stub/wikipedians_without_permission.txt

Meno25 patch 2

---

statistics/stub/range_blocks.txt
statistics/stub/users_by_number_of_article_creation.txt
statistics/stub/users_by_number_of_article_creation_with_bot.txt
statistics/stub/users_by_number_of_categories_creation.txt
statistics/stub/users_by_number_of_categories_creation_with_bot.txt
statistics/stub/users_by_number_of_portals_creation.txt
statistics/stub/users_by_number_of_portals_creation_with_bot.txt
statistics/stub/users_by_number_of_redirect_creation.txt
statistics/stub/users_by_number_of_redirect_creation_with_bot.txt
statistics/stub/users_by_number_of_templates_creation.txt
statistics/stub/users_by_number_of_templates_creation_with_bot.txt
statistics/stub/users_by_the_number_of_pages_created.txt
statistics/stub/users_with_bots_by_the_number_of_pages_created.txt

Meno25 patch 1

---

users_this_week/module.py

حذف توقيع البوت من صفحات النقاش التي تكون من نوع flow عند توزيع الأوسمة

remove bot signataure  from flow_page

---

users_this_week/README.md
users_this_week/data.py

إخفاء المستخدمين الممنوعين من **أنشط 5 مستخدمين بين المستخدمين الواعدين**

Loka1 patch 1

---

statistics/activity_of_bureaucrats.py
statistics/stub/activity_of_bureaucrats.txt

+ويكيبيديا:إحصاءات/نشاط البيروقراطيين

add activity_of_bureaucrats page

---

README.md
jobs/statistics-daily.sh
jobs/users_this_week-daily.sh
jobs/users_this_week-weekly.sh

Toolforge setup

---

statistics/list_of_portals_by_number_of_articles.py
statistics/stub/list_of_portals_by_number_of_articles.txt

ويكيبيديا:إحصاءات/قائمة البوابات حسب عدد المقالات

+ list_of_portals_by_number_of_articles page

---

cronjobs.yaml
jobs/clear_sandbox.sh
tasks/sandbox/clear.py

- مهمه قديمة كانت تعمل ب php وتم تحويلها الي python

add clear_sandbox task

---

tasks/users_this_week/data.py
tasks/users_this_week/module.py

أضافه اسم المستخدم إلى القالب الخاص بمهمة توزيع الأوسمة مستخدمو الأسبوع لحل مشكلة نقاشات التدفق

add username to template

---

.gitmodules

واجهة مستخدم سوف يتم استخدامها لادارة البوت وعرض بعض الاحصائيات

LokasBot-web

---

tasks/statistics/pages_that_are_missing_internal_links.py

use Arabic

---

jobs/distribute_medals.sh
tasks/distribute_medals/data.py
tasks/distribute_medals/module.py
tasks/distribute_medals/run.py

الكود الاساسي لمهمه توزيع الأوسمة 
التي تشمل البحث عن عدد التعديلات التاليه لكل مستخدم 
-  500
-  1000
-  2000
-  3000
-  5000
-  10000
-  20000
-  30000
-  40000
-  50000
-  60000
-  70000
-  80000
-  90000
-  100000
-  125000
-  150000
-  175000
-  200000

list_of_distribute_medals (بوت: توزيع أوسمة)

---

tasks/maintenance/bots/dead_end.py
tasks/maintenance/bots/has_categories.py
tasks/maintenance/bots/orphan.py
tasks/maintenance/bots/underlinked.py
tasks/maintenance/bots/unreferenced.py
tasks/maintenance/module.py

سجل التغيرات
- تجاهل قالب مصدر واحيد في مهمة أضافه وسم أو حذف مصدر
- تحسين حساب عدد الروابط والتصنيفات لعدم حساب المكرر

Maintenance v4.6

---

tasks/users_this_week/data.py

تحسين استعلام الإداريون الذين أجروا أكبر عدد من الأعمال الإدارية حتي لا يحسب سوي الإداريون

تحسين استعلام الإداريون الذين أجروا أكبر عدد من الأعمال الإدارية

---

gists/replace_link_from_Redirect_to_Target_in_template.py
tasks/maintenance/bots/unreferenced.py

السلام عليكم التعبير النمطي هذا <ref.*?>([.\w\W]*?)<\/ref> يحدد النصوص والجداول وكل ما خلف الوسم المغلق ذاتيًا مثل <ref name="test"/>

<ref.*?>([.\w\W]*?)<\/ref>

---

tasks/maintenance/bots/portals_merge.py
tasks/maintenance/module.py
tests/tasks/maintenance/bots/portals_merge_test.py

- إزالة شريط البوابات المكررة ودمج الشريطين	
- إزالة البوابة المحذوفة أو غير الصحيحة أو غير الموجودة
- إزالة البوابة المكررة أو وجود تحويلة لنفس البوابة ضمن شريط البوابات
- وضع البوابة في الوضع الصحيح
-   كتابة الاختبارات

بوت صيانة البوابات

---

core/utils/lua_to_python.py
core/utils/regex_scanner.py
jobs/maintenance_check.sh
jobs/maintenance_read.sh
tasks/maintenance/bots/portals_merge.py
tasks/maintenance/module.py
tasks/maintenance/tasks/portal_aliases.py
tests/core/utils/lua_to_python_test.py
tests/core/utils/regex_scanner.py
tests/tasks/maintenance/bots/portals_merge_test.py

جعل البوت يحذف البوابات الغير مستعمله بالاعتماد علي (وحدة:Portal/images/aliases)
جعل البوت يتعامل مع البوبات باستخدام الارقام

PortalsMerge bot v2

---

tasks/webcite/modules/cites/webcite.py
tasks/webcite/modules/parsed.py
tasks/webcite/run.py
tests/tasks/webcite/modules/cites/webcite.py

بوت:الإبلاغ عن رابط معطوب أو مؤرشف v1

---

tasks/webcite/check.py
tasks/webcite/module.py
tasks/webcite/modules/cite.py
tasks/webcite/modules/parsed.py
tasks/webcite/modules/request_limiter.py
tasks/webcite/read.py
tasks/webcite/test.py

اضافة url decode
اضافه خاصية  multithreading
اضافة rate limit لجغل البوت لا يورشف اكثر من ١٠ روابط في الدقيقية الواحدة

web cite v0.8

---

tasks/maintenance/module.py
tasks/webcite/check.py
tasks/webcite/data.py
tasks/webcite/module.py
tasks/webcite/modules/cite.py
tasks/webcite/modules/cites/mailinglist.py
tasks/webcite/modules/cites/map.py
tasks/webcite/modules/cites/news.py
tasks/webcite/modules/cites/newsgroup.py
tasks/webcite/modules/cites/press_release.py
tasks/webcite/modules/dateformatter.py
tasks/webcite/modules/parsed.py
tasks/webcite/modules/request_limiter.py

اضافة المزيد من قوالب الاستشهاد الي البوت

webcite v1.0

---

jobs/requests_read.sh
tasks/webcite/modules/cite.py
tasks/webcite/modules/parsed.py

حل [مشكلة](https://web.archive.org/web/20230220105353/http://penelope.uchicago.edu/holland/pliny3.html) 
> Sorry.
> This URL has been excluded from the Wayback Machine.
> 
الذي يظهر عند أرشفه بعض الروابط، والحل هو عدم وضع مسار الأرشيف كما ذكر الزميل جار الله

Webcite v1.1

---

jobs/statistics-daily.sh
tasks/statistics/cite_q.py
tasks/statistics/stub/activity_of_bureaucrats.txt
tasks/statistics/stub/administrators_activity.txt
tasks/statistics/stub/cite_q.txt
tasks/statistics/stub/wiki_maintenance/main_template.txt

[طلب الزميل ميشيل](https://ar.wikipedia.org/w/index.php?title=%D9%86%D9%82%D8%A7%D8%B4_%D8%A7%D9%84%D9%85%D8%B3%D8%AA%D8%AE%D8%AF%D9%85:%D9%84%D9%88%D9%82%D8%A7&oldid=61288092#%D8%B7%D9%84%D8%A8_%D9%8A%D9%85%D9%83%D9%86_%D8%AD%D9%84%D9%87_%D8%A8%D8%A7%D8%B3%D8%AA%D8%B9%D9%85%D8%A7%D9%84_%D8%A7%D9%84%D8%A8%D9%88%D8%AA)

ويكيبيديا:مصادر موثوقة/معاجم وقواميس وأطالس/إحصائيات

---

tasks/webcite/modules/cite.py
tasks/webcite/modules/parsed.py

جعل البوت لا يورشف اي رابط يحتوي علي هذه القائمة 
1. archive.org
2. web.archive.org
3. mail.yahoo.com
4. duckduckgo.com/?q=
5. google.com/search
6. 127.0.0.1
7. localhost
8. 0.0.0.0
9. chrome:
10. chrome-extension:
11. about:
12. moz-extension:
13. 192.168.
14. 10.
15. file:
16. edge:
17. extension:
18. safari-web-extension:
19. chrome-error:

webcite v1.2

---

tasks/maintenance/module.py
tasks/maintenance/read.py
tasks/webcite/module.py
tasks/webcite/modules/parsed.py

- اصلاح مشكله فحص اكثر من مقال عبر اكثر من thread
- تعديل الاستعلام الذي يجلب قائمة المقالات العير مراجعه عبر استخدام استلام الزميل ASammour
2. https://quarry.wmcloud.org/query/71976
3. https://quarry.wmcloud.org/query/71975

fix thread logic

---

tasks/maintenance/bots/dead_end.py
tasks/maintenance/bots/protection.py
tasks/maintenance/module.py
tests/tasks/maintenance/bots/protection_test.py

اعادة تفعيل بوت (إضافة/إزالة قالب نهاية مسدودة) بعد اعادة كتابة كود البوت من جديد

Maintenance v4.9.0

---

tasks/webcite/check.py
tasks/webcite/module.py
tasks/webcite/modules/cite.py
tasks/webcite/modules/cites/module.py
tasks/webcite/modules/parsed.py

1. الغاء استخدام دالة urllib.parse.unquote في المسار ومسار الارشيف
2. اصلاح مشكله تشغيل نفس الصفحة علي اكثر من thread

Webcite v1.2.3

---

tasks/webcite/module.py
tasks/webcite/modules/parsed.py

- تجاهل الصفحات التي تم انشاءها قبل ثلاث ساعات من الان لتحسين النتائج

webcite_v1.2.3

---

tasks/maintenance/bots/underlinked.py
tasks/maintenance/module.py

اعاده تفعيل بوت (إضافة/إزالة قالب وصلات قليلة) بعد اعادة كتابة الكود

Maintenance v5.2.0

---

core/utils/file.py
jobs/maintenance_check.sh
jobs/maintenance_read.sh
tasks/maintenance/bots/template_redirects.py
tasks/maintenance/module.py
tasks/maintenance/task/awb/template_redirects.py

1. اضافة مهمة استبدال القوالب بالاعتماد علي (ويكيبيديا:AutoWikiBrowser/Template redirects) (تعمل كمهمة اضافيه)

Maintenance v5.3.0 (ويكيبيديا:AutoWikiBrowser/Template redirects)

---

jobs/maintenance_check.sh
tasks/maintenance/module.py
tasks/maintenance/task/skip/ignore_pages.py

اضافة (مستخدم:LokasBot/تجاهل مهمة صيانة المقالات) لحل مشكل تضارب البوتات

Maintenance v5.4.0

---

tasks/statistics/administrators_activity.py
tasks/statistics/module.py

1. حل مشكلة عدم تحديث (ويكيبيديا:إحصاءات/نشاط الإداريين) بعد اخر اصدار 
2. تغير وصف المهمة حتي يشمل رقم الاصدار لمزيد من التتبع

Statistics_v2.1.2

---

jobs/maintenance_check.sh
tasks/maintenance/bots/rename_template_parameters.py
tasks/maintenance/module.py
tasks/maintenance/task/awb/rename_template_parameters.py

اضاففة تعريب الوسائط بالاعتماد علي (ويكيبيديا:AutoWikiBrowser/Rename template parameters)

Maintenance v5.5.0

---

tasks/maintenance/bots/stub.py
tasks/maintenance/module.py

Maintenance v5.6.0

---

cronjobs.yaml
database/models.py
jobs/read.sh
tasks/maintenance/module.py
tasks/maintenance/read.py
tasks/webcite/modules/parsed.py
tasks/webcite/read.py

- جعل جلب الصفحات يتم عبر تخزين اخر وقت تم فحص الصفحات فيه ويجلب الصفحات الجديد بعد ذلك الوقت ثم يخزن اخر وقت فحص جديد في قاعدة البيانات (وذلك لتقليل الضغط علي السيرفر)

Maintenance v5.6.4

---

database/engine.py
database/helpers.py
database/models.py
tasks/maintenance/check.py
tasks/maintenance/module.py
tasks/maintenance/read.py
tasks/maintenance/task/add/orphan_add.py
tasks/maintenance/task/add/orphan_remove.py
tasks/webcite/check.py
tasks/webcite/module.py
tasks/webcite/read.py

البدا في الاعتماد علي قاعدة mysql

Start use mysql db

---

tasks/check_usernames/check/check.py
tasks/check_usernames/check/modules.py
tasks/check_usernames/load/load.py

اصلاح مشكله التشغيل المستمر للمهمه (السبب عمليه دمج غير صحيحة)

Check usernames v2.1.0

---

tasks/requests/add_category/read.py
tasks/requests/cite/load.py
tasks/requests/cite/read.py
tasks/requests/link_replacement/read.py
tasks/requests/portal_distribution/read.py
tasks/requests/template_distribution/read.py

1. اصلاح اقل عدد لتنفيذ
2. اصلاح مهمه الارشفه

اصلاح بعض الاخطاء في مهمه الطلبات

---

.gitmodules

حذف موقع البوت وجعله منفصل كون لا فائدة من ربطه مع هذا المستودع ويمكن التعديل عليه مباشرة

remove LokasBot-web

---

jobs/statistics-daily.sh
tasks/statistics/module.py
tasks/statistics/sandboxs_users_need_to_review.py
tasks/statistics/stub/sandboxs_users_need_to_review.txt

ويكيبيديا:ملاعب مستخدمين تحتاج لمراجعة

ويكيبيديا:ملاعب مستخدمين تحتاج لمراجعة

---

tasks/statistics/cite_q.py

1. اصلاح مشكله وجود قالب ووحده بنفس الاسم (Cite_Q) [[1](https://ar.wikipedia.org/w/index.php?title=%D9%86%D9%82%D8%A7%D8%B4_%D8%A7%D9%84%D9%85%D8%B3%D8%AA%D8%AE%D8%AF%D9%85:%D9%84%D9%88%D9%82%D8%A7&oldid=62139185)]

statistics_v2.2.1

---

tasks/check_usernames/check/modules.py

1. عدم ارسال التنبيه الي المستخدمين الذين تم ارسال لهم التنبيه بالفعل

check_usernames_v2.2.0

---

tasks/maintenance/bots/portals_merge.py
tasks/requests/core/module.py
tasks/requests/portal_distribution/run.py

1. اصلاح مشكله اضافه البوابه الي الصفحات التي تحتوي نفس الاسم لكن عباره عن تحويله 
2. تعديل نص ملخص التعديل
3. تعديل ترتيب القوالب
4. اصلاح مشكله تنفيذ الطلبات للمستخدمين ذات العدد الاقل من ٣٠٠٠ تعديل

ويكيبيديا طلبات توزيع بوابة v2

---

jobs/requests_read.sh
tasks/requests/core/module.py
tasks/requests/link_replacement/read.py

1. اضافه داله التحقق من صلاحية المستخدم 
2. اضافه امكانيه الاشاره الي المستخدم ذات صلايحة الادارة حتي يمكنه التحقق من الطلب

ويكيبيديا_طلبات_استبدال_الوصلات_v2

---

tasks/requests/replace_template/load.py

اضافه استعلام 
* [[:قالب:اسم القالب القديم]]>[[:قالب:اسم القالب الجديد]]>[[:تصنيف:اسم التصنيف المحدد]]

ويكيبيديا_طلبات_استبدال_القوالب_v2

---

cronjobs.yaml
database/engine.py
jobs/read_last_day.sh
tasks/webcite/module.py
tasks/webcite/read_last_day.py

1. تعديل مهمة بوت أرشفه الروابط حتى يمكنه فحص تعديلات أمس مع بداية كل يوم جديد لمنع عدم أرشفه بعض الروابط (هذا الكود بشكل مبدئي لحين  تعديل كود المهمة ليتم أضافه كود تتبع حتى يضع الصفحة بشكل تلقائي في المهمة مرة أخرى في حاله وجد المزيد من الروابط تحتاج للعمل)
2. تفعيل مهمه month-statistics

webcite_V1.6.2

---

cronjobs.yaml
jobs/read_last_day.sh
tasks/webcite/module.py
tasks/webcite/read_last_day.py

- جعل بوت الارشفه يضيف تعديلات يوم امس في الثريد رقم ٣ لاعاده الفحص مره اخري لمنع هروب اي صفحات من بوت الارشفه

webcite v1.6.3

---

database/helpers.py
tasks/maintenance/check.py
tasks/maintenance/module.py
tasks/webcite/check.py
tasks/webcite/module.py

- اضافه داله update_page_statuses_to_pending لتحديث جميع الصفحات بعد عمليه الفحص، الهدف من هذه الداله حل مشكله عدم تحديث حاله بعض الصفحات اثناء عمليه الفحص

Add update_page_statuses_to_pending() to update all pages after check

---

jobs/month_statistics.sh
tasks/autoCreatePages/create.py

- اضافه بوت جديد يقوم بانشاء التصنيفات المطلوبه لمهام مثل بوت الارشفه والصيانه اذا لم تكن موجوده بشكل الي

Auto create pages bot

---

tasks/autoCreatePages/create.py
tasks/month_statistics/stub/update.txt
tasks/month_statistics/update.py
tasks/requests/add_category/run.py

- اضافه ال api الخاص بموقع pageviews حسب طلب دكتور طاهر [[1]](https://ar.wikipedia.org/wiki/%D9%86%D9%82%D8%A7%D8%B4_%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7:%D8%A5%D8%AD%D8%B5%D8%A7%D8%A1%D8%A7%D8%AA_%D8%A7%D9%84%D8%B4%D9%87%D8%B1#c-Dr-Taher-20230506121200-Dr-Taher-20230228203100)

Month statustices v2

---

tasks/requests/portal_distribution/load.py
tasks/requests/portal_distribution/read.py

اضافه امكانيه توزيع البوابه علي المقال بدون الاعتماد علي التصنيفات او القوالب او البوابات (مفيده للمستخدمين الذي يريدون توزيع البوابه علي قائمة مقالات مخصصه)

ويكيبيديا_طلبات_توزيع_بوابة_v2

---

tasks/requests/portal_distribution/read.py

جعل ويكيبيديا:طلبات إزالة (بوابة، تصنيف، قالب) تعمل بعد تعديل الاداري

جعل ويكيبيديا:طلبات إزالة (بوابة، تصنيف، قالب) تعمل بعد تعديل الاداري

---

config/config.ini
jobs/clear_sandbox.sh
tasks/copypatrol/update.py

1. اضافه بوت جلب عدد الحالات المفتوحه في موقع [copypatrol](https://copypatrol.toolforge.org/ar/) حسب [اقترح](https://ar.wikipedia.org/w/index.php?title=%D9%86%D9%82%D8%A7%D8%B4_%D8%A7%D9%84%D9%85%D8%B3%D8%AA%D8%AE%D8%AF%D9%85:Dr-Taher&oldid=62372971#%D8%B3%D8%A4%D8%A7%D9%84_%D8%A8%D8%AE%D8%B5%D9%88%D8%B5_%D8%A7%D9%82%D8%AA%D8%B1%D8%A7%D8%AD%D9%83_%D8%A7%D9%84%D8%A3%D8%AE%D9%8A%D8%B1) دكتور طاهر (حتي يتم الانتهاء من التذكرة)

copypatrol

---

jobs/users_this_week-weekly.sh
tasks/missingtopics/update.py

[اضافه بوت (ويكيبيديا:مقالات مطلوبة حسب الاختصاص)](https://ar.wikipedia.org/wiki/%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7:%D9%85%D9%82%D8%A7%D9%84%D8%A7%D8%AA_%D9%85%D8%B7%D9%84%D9%88%D8%A8%D8%A9_%D8%AD%D8%B3%D8%A8_%D8%A7%D9%84%D8%A7%D8%AE%D8%AA%D8%B5%D8%A7%D8%B5)  حسب طلب دكتور طاهر [[1](https://ar.wikipedia.org/w/index.php?title=%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7:%D8%A7%D9%84%D9%85%D9%8A%D8%AF%D8%A7%D9%86/%D8%AA%D9%82%D9%86%D9%8A%D8%A9&oldid=62395183)]

بوت:ويكيبيديا:مقالات مطلوبة حسب الاختصاص

---

tasks/missingtopics/update.py

جعل قائمة الصفحات تاتي بشكل الي عبر استعلام من قاعده البيانات

بوت:تحديث مقالات مطلوبة حسب الاختصاص v1.1.0

---

toolforge/jobs/requests_read.sh

- ايقاف بوت فحص الاسماء المخالفه عن العمل لحين انتهاء النقاش

disable check_usernames bot

---

tasks/distribute_medals/data.py
tasks/distribute_medals/module.py
toolforge/jobs/users_this_week-weekly.sh

1. تشغيل مهمة توزيع الاوسمة
2. جعل الاستعلام يعتمد علي التعديلات الحية غير المحذوف
3. تعديل تعليق وصف المهمة
4. جعل المهمة تعمل بشكل اسبوعي

Distribute medals v1.2

---

tasks/missingtopics/update.py

- اضافة اسماء المقالات بالانجليزيه اذا كان موجود
-

Missingtopics v2.0.0

---

tasks/distribute_medals/module.py
tasks/distribute_medals/run.py
tasks/distribute_medals/test.py

1. اضافه كلاس SignatureManager حتي يجلب اسم عشوائي مع استنناء الاسم المتواجد الان حسب طلب دكتور طاهر
2. تعديل صيغة اسم العنوان من "تهانينا" الي "وسام (عدد التعديلات) تعديل! " حسب طلب ابو هشام
3. اضافة get_user_name حتي تجلب اسم المستخدم من التوقيع لاستخدمه في SignatureManager
4. اصلاحات عامة في الكود 
5. اضافه logging

Distribute medals v1.3.0

---

tasks/statistics/cite_q.py
tasks/statistics/module.py
toolforge/cronjobs.yaml
toolforge/jobs/statistics-daily.sh
toolforge/jobs/statistics-weekly.sh
toolforge/jobs/users_this_week-weekly.sh

1. جعل عرض الصفوف يتم حسب "عدد مرات الاستشهاد" في "ويكيبيديا:مصادر موثوقة/معاجم وقواميس وأطالس/إحصائيات"
2. نقل ويكيبيديا:مصادر موثوقة/معاجم وقواميس وأطالس/إحصائيات الي جوب جديد وجعلها تعمل بشكل اسبوعي وليس يومي
3. انشاء جوب جديد مسئول عن تحديثات الاحصائيات التي تعمل بشكل اسبوعي

(statistics_v2.2.2) some fix in  cite_q.py + add new job 

---

core/utils/helpers.py
tasks/requests/link_replacement/run.py
tasks/requests/portal_distribution/run.py
tasks/requests/remove/run.py
tasks/requests/replace_template/load.py
tasks/requests/replace_template/read.py
tasks/requests/replace_template/run.py
tasks/requests/template_distribution/run.py

1. جعل ويكيبيديا:طلبات استبدال القوالب تفذ طلبات المحررين الذين يملكوا اكثر من ٣٠٠٠ تعديل 
2. تم اضافه نطاق البوابه وويكيبيديا و المستخدم الي مهمة ويكيبيديا:طلبات استبدال القوالب
3. تم اضافة صفحة ويكيبيديا:طلبات استبدال القوالب/إيقاف
4. تم تعديل تريتيب الصفحات بحيث تبدا عمليه التنفيذ من النطاقات الاعلي الي الاقل (الهدف جعل نطاق 0 اخر شي)
5.

Requests v2

---

tasks/month_statistics/update.py

1. جعل البوت يجلب رقم الشهر تلقائيا
2. إصلاحات عامه علي الكود
3. جعل البوت لا يعمل لا يوم ١ في الشهر الجديد (مؤقتا)

Month statistics v3

---

tasks/autoCreatePages/create.py

1. جعل البوت يعمل بشكل تلقائي في بدايه كل شهر 
2. جعل البوت يتعرف علي اسم الشهر بنفسه 
3. اضافه كلاس جديد يجلب اسم الشهر العربي من رقم الشهر 
4. اضافه الشرح الكافي للبوت 
5. استخدام oop في تحسين الكود

Auto create pages v2

---

tasks/maintenance/bots/rename_reference_section.py

بوت استبدال اعاده تسميه قسم مراحع الي المراجع حسب طلب الزميل [محمد ماجد السورميري](https://ar.wikipedia.org/w/index.php?title=%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7:%D8%A7%D9%84%D9%85%D9%8A%D8%AF%D8%A7%D9%86/%D8%AA%D9%82%D9%86%D9%8A%D8%A9&oldid=63348844#%D8%AA%D8%B9%D8%B1%D9%8A%D9%81_%D8%A7%D9%84%D9%85%D8%B1%D8%A7%D8%AC%D8%B9)
```
== المراجع ==
== مراجع ==
هذا القسم فقط الذي سوف يتم عمل اعاده تسميه له
== مراجع ٢ ==
== مراجع شش ==
=== مراجع ===
```
```
== المراجع ==
==المراجع==
هذا القسم فقط الذي تم عمل اعاده تسميه له
== مراجع ٢ ==
== مراجع شش ==
=== مراجع ===
```
سوف يتم تفعيله متي تم وضع الخلاصه

Rename reference section bot

---

gists/Sources_of_identifiers/README.md
gists/Sources_of_identifiers/from_csv_to_sqlite.py
gists/Sources_of_identifiers/load_diff.py

1. اكواد [مهمة إزالة استشهادات خاطئة التي طلبها الزميل](https://ar.wikipedia.org/wiki/%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7:%D8%A7%D9%84%D9%85%D9%8A%D8%AF%D8%A7%D9%86/%D8%AA%D9%82%D9%86%D9%8A%D8%A9/2023/%D9%8A%D9%88%D9%86%D9%8A%D9%88#%D8%A5%D8%B2%D8%A7%D9%84%D8%A9_%D8%A7%D8%B3%D8%AA%D8%B4%D9%87%D8%A7%D8%AF%D8%A7%D8%AA_%D8%AE%D8%A7%D8%B7%D8%A6%D8%A9) مشيل منذ فترة  حتي يمكن الرجوع اليها في المستقبل

مهمة إزالة استشهادات خاطئة

---

toolforge/jobs/statistics-daily.sh

ايقاف ثلاث صفحات عن العمل لحين اصلاح الاستعلام، الاستعلام يحتاج لاعاده كتابه من جديد

ايقاف بعض الصفحات عن العمل لحين اصلاح الاستعلان

---

README.md
toolforge/cronjobs.yaml
toolforge/cronjobs1.yaml
toolforge/cronjobs2.yaml

فصل المهام علي اكثر من سيرفر 
- جعل بوت الصيانه والارشفه علي سيرفر 
- جعل بوت الاحصائيات و الطلبات علي سيرفر

فصل المهام علي اكثر من سيرفر

---

tasks/requests/link_replacement/module.py
tasks/statistics/bot_wars.py
tasks/statistics/statistics_pages_may_be_down_that_need_to_be_checked.py
tasks/statistics/stub/bot_wars.txt
tasks/statistics/stub/ٍstatistics_pages_may_be_down_that_need_to_be_checked.txt

1. اضافه مستخدم:LokasBot/حروب البوت
2. مستخدم:LokasBot/صفحات إحصاءات قد تكون معطلة تحتاج للفحص

add new pages statisticsv2.3.2

---

tasks/statistics/list_of_wikipedians_by_number_of_files_uploaded.py
tasks/statistics/module.py
tasks/statistics/stub/list_of_wikipedians_by_number_of_files_uploaded.txt

+ ويكيبيديا:قائمة الويكيبيديين حسب عدد الملفات المرفوعة

add list_of_wikipedians_by_number_of_files_uploaded.py

---

tasks/statistics/module.py
tasks/statistics/stub/unusually_long_ip_blocks.txt
tasks/statistics/stub/unusually_long_user_blocks.txt
tasks/statistics/unusually_long_ip_blocks.py
tasks/statistics/unusually_long_user_blocks.py
toolforge/jobs/statistics-daily.sh

+ ويكيبيديا:تقارير قاعدة البيانات/مستخدمين محظورين لمدة طويلة بشكل غير عادي
+ ويكيبيديا:تقارير قاعدة البيانات/عناوين IP المحظورة لمدة طويلة بشكل غير عادي

Statistics v2.4.4

---

tasks/statistics/cite_q.py
tasks/statistics/module.py
tasks/statistics/stub/articles_containing_linked_email_addresses.txt
tasks/statistics/stub/cite_q.txt
tasks/statistics/stub/indefinitely_blocked_ips.txt

1. تحديث عنوان ويكيبيديا:مصادر موثوق بها/معاجم وقواميس وأطالس/إحصائيات بعد عمل النقل الي الاسم الجديد
2. اصلاحات علي بوت الاحصائيات

statistics_V2.5.1

---

tasks/statistics/cite_q.py
tasks/statistics/module.py

تحديث اسم الصفحة لحل مشكله عدد المعاجم في ويكيبيديا:مصادر موثوق بها/معاجم وقواميس وأطالس/إحصائيات

statistics_V2.5.2

---

tasks/users_this_week/daily.py

[الغاء تحديث صفحه ويكيبيديا:مستخدمو الأسبوع الأكثر نشاطا حسب طلب الزميل ابراهيم والاعتماد علي كود wikitext](https://w.wiki/86Hw)

disable update homepage  https://w.wiki/86Hw

---

gists/pages.py
tasks/statistics/wikidata/current_events_recent_obituaries.py
toolforge/jobs/statistics-daily.sh

1. اعاده تشغيل صفحه [[بوابة:أحداث جارية/شريط جانبي/وفيات حديثة](https://ar.wikipedia.org/wiki/%D8%A8%D9%88%D8%A7%D8%A8%D8%A9:%D8%A3%D8%AD%D8%AF%D8%A7%D8%AB_%D8%AC%D8%A7%D8%B1%D9%8A%D8%A9/%D8%B4%D8%B1%D9%8A%D8%B7_%D8%AC%D8%A7%D9%86%D8%A8%D9%8A/%D9%88%D9%81%D9%8A%D8%A7%D8%AA_%D8%AD%D8%AF%D9%8A%D8%AB%D8%A9)](بوابة:أحداث جارية/شريط جانبي/وفيات حديثة) بعد توقف بوت ListeriaBot حسب طلب الزميل [محمد](https://ar.wikipedia.org/w/index.php?title=%D9%86%D9%82%D8%A7%D8%B4_%D8%A7%D9%84%D8%A8%D9%88%D8%A7%D8%A8%D8%A9:%D8%A3%D8%AD%D8%AF%D8%A7%D8%AB_%D8%AC%D8%A7%D8%B1%D9%8A%D8%A9/%D8%B4%D8%B1%D9%8A%D8%B7_%D8%AC%D8%A7%D9%86%D8%A8%D9%8A/%D9%88%D9%81%D9%8A%D8%A7%D8%AA_%D8%AD%D8%AF%D9%8A%D8%AB%D8%A9&oldid=65277572)

add current_events_recent_obituaries

---

tasks/statistics/wikidata/current_events_recent_obituaries.py

[اصلاح مشكلة الترتيب حسب طلب الزميل محمد](https://ar.wikipedia.org/w/index.php?title=%D9%86%D9%82%D8%A7%D8%B4_%D8%A7%D9%84%D8%A8%D9%88%D8%A7%D8%A8%D8%A9:%D8%A3%D8%AD%D8%AF%D8%A7%D8%AB_%D8%AC%D8%A7%D8%B1%D9%8A%D8%A9/%D8%B4%D8%B1%D9%8A%D8%B7_%D8%AC%D8%A7%D9%86%D8%A8%D9%8A/%D9%88%D9%81%D9%8A%D8%A7%D8%AA_%D8%AD%D8%AF%D9%8A%D8%AB%D8%A9&oldid=65600705)

statistics_wikidata_v0.2

---

tasks/maintenance/bots/dead_end.py
tasks/maintenance/bots/has_categories.py
tasks/maintenance/bots/orphan.py
tasks/maintenance/bots/protection.py
tasks/maintenance/bots/underlinked.py
tasks/maintenance/bots/unreferenced.py
tasks/maintenance/bots/unreviewed_article.py

Reverts LokasWiki/LokasBot#320

Revert "maintenance_V5.10.0 add:remove template with \n"

---

tasks/maintenance/bots/dead_end.py
tasks/maintenance/bots/has_categories.py
tasks/maintenance/bots/orphan.py
tasks/maintenance/bots/protection.py
tasks/maintenance/bots/underlinked.py
tasks/maintenance/bots/unreferenced.py
tasks/maintenance/bots/unreviewed_article.py

Reverts LokasWiki/LokasBot#321

Revert "Revert "maintenance_V5.10.0 add:remove template with \n""

---

tasks/users_this_week/README.md
tasks/users_this_week/data.py

Reverts LokasWiki/LokasBot#352

Revert "Add normalize media wiki link tables (users this week)"

---

tasks/ci_cd_log_task/bot.py
toolforge/cronjobs.yaml
toolforge/cronjobs1.yaml
toolforge/cronjobs2.yaml
toolforge/jobs/ci_cd_log_task.sh

This update to the script responsible for sending bot update notifications on Wikipedia includes several improvements to ensure the accuracy and effectiveness of the messages sent. The changes include:
1. **Added Tool Name to Title:**
- The tool name, derived from the `LOGNAME` environment variable, has been included in the title of the notification page on Wikipedia. This addition will help accurately identify the tool used in notifications.
2. **Enhanced Update Details:**
- The update details section in the bot's notification has been improved to include more comprehensive information, such as:
- Bot version.
- Last Commit message.
- Link to the Commit on GitHub.
- Date and time of the last Commit.
- Date and time of the bot's operation.
- Name of the last contributor to the update.
3. …

add test-pull task

---

.github/workflows/add_ssh_deploy_server.yml

This PR introduces a new GitHub Actions workflow named `add_ssh_deploy_server.yml` that automates the deployment process for the LokasBot server. The workflow is triggered on every push to the `main` branch.
**Key Features:**
- **SSH Deployment**: Utilizes the `appleboy/ssh-action` to securely connect to the server using SSH and execute deployment scripts.
- **Server Automation**: After connecting to the server, the workflow switches to the `lokasbot` user and runs the `pull.sh` script to fetch the latest updates from the repository.
- **Security**: Sensitive data such as the server host, username, port, and password are securely managed using GitHub Secrets.
This update will streamline the deployment process, ensuring that the latest code is automatically pulled to the server whenever …

Add SSH Deployment Workflow for LokasBot

---

tasks/autoCreatePages/create.py

1. إضافة انشاء تصنيفات بشكل شهري علي شاكلة "تصنيف:مراجعات الزملاء يوليو 2024" حسب طلب الزميل @GergesShamon

autoCreatePages_v2.1.0

---

tasks/maintenance/data/orphan/add.py
tasks/maintenance/data/orphan/remove.py
tasks/maintenance/module.py

اصلاح استعلام جلب المقالات التي يجب اضافه قالب يتيمه لها وحذف قالب يتيمة منها

maintenance V5.11.0

---

tasks/missingtopics/update.py

This pull request includes an update to the SQL query in the `tasks/missingtopics/update.py` file to improve the accuracy of the data retrieval process.
Database query update:
* [`tasks/missingtopics/update.py`](diffhunk://#diff-52f8fce7e3b7bc85b92197214843a49c34d6f18124f2d53bbe3a2e6196cad71aL53-R59): Modified the SQL query to join the `linktarget` table using `linktarget.lt_id` and `pagelinks.pl_target_id`, replaced `pl_title` with `lt_title`, and updated the conditions and order by clause to use `lt_title` instead of `pl_title`.Update database query to use linktarget table for improved query performance and accuracy

Refactor SQL query in missing topics update script

---

tasks/missingtopics/README.md
tasks/missingtopics/entities/topic_entity.py
tasks/missingtopics/main.py
tasks/missingtopics/observers/logging_observer.py
tasks/missingtopics/observers/observer_protocol.py
tasks/missingtopics/repositories/article_repository.py
tasks/missingtopics/repositories/topic_repository.py
tasks/missingtopics/use_cases/update_missing_topics.py
tests/tasks/missingtopics/test_article_repository.py
tests/tasks/missingtopics/test_logging_observer.py
toolforge/cronjobs2.yaml
toolforge/jobs/missingtopics.sh
toolforge/jobs/statistics-weekly.sh

This pull request introduces a comprehensive logging system and several enhancements to the `tasks/missingtopics` module. The most important changes include the addition of a logging system, updates to the `Article` class, and modifications to the observer pattern.
* [`tasks/missingtopics/README.md`](diffhunk://#diff-82981d9bff291c26bfce00b086cfc0b3dddca550d9384569b7ad74c032baf236R350-R447): Added a detailed section on the logging system, including log levels, configuration, observer pattern, log events, usage examples, and testing.
* [`tasks/missingtopics/main.py`](diffhunk://#diff-2b59bdc97140c4f31d6b2cafc1602fb51b740fcaaaf55221559c83f6d0a4cf23L3-R27): Implemented logging configuration with a stream handler for console output and set specific log levels for different loggers.
* …

Missingtopics v3.2

---

CHANGELOG.md
tasks/missingtopics/README.md

This pull request includes significant updates to the `CHANGELOG.md` file and the `tasks/missingtopics/README.md` file. The changes involve adding new features, implementing design patterns, and enhancing the documentation for better clarity and maintainability.
* [`CHANGELOG.md`](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL8-R28): Updated with new version 1.17.2, detailing added features, changes, and technical updates, including the implementation of the Repository Pattern, Configuration Pattern, and Command Pattern. Enhanced logging system and support for Python 3.6+ were also added. [[1]](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL8-R28) [[2]](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f25 …

Missing topics v3.2.1

---

tasks/requests/add_category/load.py
tasks/requests/portal_distribution/load.py
tasks/requests/remove/load.py
toolforge/jobs/requests_read.sh

This pull request includes several changes to improve database queries and enable certain Python scripts. The most important changes include updating SQL queries to use the `linktarget` table for better performance and re-enabling multiple Python scripts in the `toolforge` job.
Improvements to database queries:
* [`tasks/requests/add_category/load.py`](diffhunk://#diff-e4bda94545453a8d5f69463527ba6c65d5e850e83e3ef4c07ac62165cdbbb9baL28-R30): Updated the query to use `linktarget` table for joining with `pagelinks` to improve performance.
* [`tasks/requests/portal_distribution/load.py`](diffhunk://#diff-b123900e962b285773d2bb8e539f672c2e6928c2cc2b6c5300c4f0c1e1143348L15-R22): Modified multiple queries to join `pagelinks` with `linktarget` for better efficiency. …

Requests   add category
